export const jobTitlesByCategory = {
    Sales: [
      "OS APPTS Outside Sales - Apparatus",
      "OS RESCU Outside Sales - Rescue Tool Specialist",
      "OS SALES Outside Sales",
      "OS SALES PT Outside Sales Part Time",
      "OS TMLDR Outside Sales - Team Leader",
      "OSRESCPT Outside Sales - Rescue Spec PT",
      "OSRESMG Outside Sales Rescue Tool Manager",
      "OSSLSMGR Outside Sales Manager",
      "OSSRLE Outside Sales Rep - Law Enforcement",
    ],
    "AP/AR": [
      "ACCPAY Accounts Payable Associate",
      "ACCPAYSR Sr. Accounts Payable Specialist",
      "APMGR Accounts Payable Manager",
      "ARMGR Accounts Receivable Manager",
    ],
    MFG: [
      "MFG ASSEMB Manufacturing Assembler",
      "MFG ELECTR Manufacturing Electrician",
      "MFG ENGINEER Manufacturing Engineer",
      "MFG SUPERVISOR Manufacturing Supervisor",
    ],
    OPS: [
      "OPSMGR Operations Manager - Regional",
      "OPSSPEC Operations Specialist - Regional",
    ],
    Service: [
      "SER WRITER Service Writer",
      "SERV IH Service Technician - IN HOUSE",
      "SERV MGR Service Manager",
      "SERV TECH SUPP IH Service Technician - Suppression IH",
      "SERVAP Service Technician-Air Products",
      "SERVAPPT Service Technician-Air Products Part Time",
      "SERVCOUR Service Courier and Technician",
      "SERVDC Service Technician-DC Shop",
      "SERVGASP Service Technician-Gas Detection Part Time",
      "SERVHYBR Service Technician-Hybrid",
      "SERVHYDP Service Technician-Hydro Testing Part Time",
      "SERVHYDR Service Technician-Hydro Testing",
      "SERVMDC Service Manager DC Shop",
      "SERVMGR REGIONAL Service Manager Regional",
      "SERVOPMG Service Operations Manager",
      "SERVOPSP Service Operations Specialist",
      "SERVRESC Service Technician-Rescue Products",
      "SERVRESP Service Technician-Rescue Products Part Time",
      "SERVSUP Service Technician-Suppression",
      "SERVTECH APPTS Service Technician-Apparatus",
    ],
    Warehouse: [
      "WHSESPEC Warehouse Specialist",
      "WHSE MGR Warehouse Manager",
      "WHSESUPR Warehouse Supervisor",
    ],
    Exec: [
      "VP FIREMKTSP VP Fire Market Sales Programs",
      "VP OPE Vice President Operations",
      "VP-REG Vice President Regional",
      "VP TRAIN Vice President Training",
      "VPGOVSLS VP Government Sales",
      "VPTREAS VP, Treasury",
      "VPUNIFMFG VP of Uniform Manufacturing",
      "VPZONE Vice President Zone",
      "BD DIR Board of Directors",
      "SVP APP Senior Vice President Apparatus",
    ],
    Retail: [
      "RTLSLMGR Retail Sales Manager",
      "RTLSLSA Retail Sales Associate",
      "RTLSLSPT Retail Sales Associate Part Time",
      "RTSTRMGR Retail Store Manager",
    ],
    Uniform: [
      "UNIDESSPEC Uniform Design Specialist",
      "UNIF DSN ST MGR Uniform Design Studio Manager",
      "UNIFCSR Uniform Customer Service",
      "UNIFORM EMBSPEC Embroiderer",
      "UNIFORM SPEC Uniform Specialist",
      "UNISTRASSOC Uniform Store Associate",
      "UNISTRMGR Uniform Store Manager",
    ],
    IT: [
      "IT DIRECTOR IT Director",
      "IT SPECL IT Specialist",
      "IT SPECL MOBILE DEV Help Desk IT Support Specialist/Mobile Device Administrator",
      "ITMGR IT Manager",
    ],
    Misc: [
      "BID SALESSP Bid Sales Specialist",
      "BUSINTELANALYST Business Intelligence Analyst",
      "COLLSPEC Collection Specialist - Regional",
      "CONTADMN Contract Administrator",
      // Add more job titles for Misc
    ],
  };